//------------------------------------------------------------------------------
// <auto-generated>
//   This code was generated by a tool.
//
//    Umbraco.ModelsBuilder.Embedded v8.10.0
//
//   Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Linq.Expressions;
using System.Web;
using Umbraco.Core.Models;
using Umbraco.Core.Models.PublishedContent;
using Umbraco.Web;
using Umbraco.ModelsBuilder.Embedded;

namespace LingsCars.Models.ContentTypes
{
	/// <summary>Home Page</summary>
	[PublishedModel("homePage")]
	public partial class HomePage : PublishedContentModel, INavigation, IPageHeader, ISEO
	{
		// helpers
#pragma warning disable 0109 // new is redundant
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.10.0")]
		public new const string ModelTypeAlias = "homePage";
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.10.0")]
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.10.0")]
		public new static IPublishedContentType GetModelContentType()
			=> PublishedModelUtility.GetModelContentType(ModelItemType, ModelTypeAlias);
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.10.0")]
		public static IPublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<HomePage, TValue>> selector)
			=> PublishedModelUtility.GetModelPropertyType(GetModelContentType(), selector);
#pragma warning restore 0109

		// ctor
		public HomePage(IPublishedContent content)
			: base(content)
		{ }

		// properties

		///<summary>
		/// navLinks
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.10.0")]
		[ImplementPropertyType("navLinks")]
		public global::System.Collections.Generic.IEnumerable<global::Umbraco.Web.Models.Link> NavLinks => this.Value<global::System.Collections.Generic.IEnumerable<global::Umbraco.Web.Models.Link>>("navLinks");

		///<summary>
		/// Page Content
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.10.0")]
		[ImplementPropertyType("pageContent")]
		public global::System.Web.IHtmlString PageContent => this.Value<global::System.Web.IHtmlString>("pageContent");

		///<summary>
		/// Popular Vehicles
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.10.0")]
		[ImplementPropertyType("popularVehicles")]
		public global::System.Collections.Generic.IEnumerable<global::Umbraco.Core.Models.PublishedContent.IPublishedContent> PopularVehicles => this.Value<global::System.Collections.Generic.IEnumerable<global::Umbraco.Core.Models.PublishedContent.IPublishedContent>>("popularVehicles");

		///<summary>
		/// Add to Nav: If true will be added to the nav bar
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.10.0")]
		[ImplementPropertyType("addToNav")]
		public bool AddToNav => global::LingsCars.Models.ContentTypes.Navigation.GetAddToNav(this);

		///<summary>
		/// Page Header Background: Select image to be displayed in background of header.
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.10.0")]
		[ImplementPropertyType("pageHeaderBackground")]
		public global::Umbraco.Core.Models.PublishedContent.IPublishedContent PageHeaderBackground => global::LingsCars.Models.ContentTypes.PageHeader.GetPageHeaderBackground(this);

		///<summary>
		/// Page Heading
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.10.0")]
		[ImplementPropertyType("pageHeading")]
		public string PageHeading => global::LingsCars.Models.ContentTypes.PageHeader.GetPageHeading(this);

		///<summary>
		/// Should follow links when indexing
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.10.0")]
		[ImplementPropertyType("indexingFollowLinks")]
		public bool IndexingFollowLinks => global::LingsCars.Models.ContentTypes.SEO.GetIndexingFollowLinks(this);

		///<summary>
		/// Should Index Page
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.10.0")]
		[ImplementPropertyType("indexPage")]
		public bool IndexPage => global::LingsCars.Models.ContentTypes.SEO.GetIndexPage(this);

		///<summary>
		/// Meta Description: Enter description to be displayed on search result pages.
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.10.0")]
		[ImplementPropertyType("metaDescription")]
		public string MetaDescription => global::LingsCars.Models.ContentTypes.SEO.GetMetaDescription(this);

		///<summary>
		/// Page Title: Enter name that should be displayed in browser tab.
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.10.0")]
		[ImplementPropertyType("pageTitle")]
		public string PageTitle => global::LingsCars.Models.ContentTypes.SEO.GetPageTitle(this);
	}
}
