//------------------------------------------------------------------------------
// <auto-generated>
//   This code was generated by a tool.
//
//    Umbraco.ModelsBuilder.Embedded v8.10.0
//
//   Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Linq.Expressions;
using System.Web;
using Umbraco.Core.Models;
using Umbraco.Core.Models.PublishedContent;
using Umbraco.Web;
using Umbraco.ModelsBuilder.Embedded;

namespace LingsCars.Models.ContentTypes
{
	// Mixin Content Type with alias "pageHeader"
	/// <summary>Page Header</summary>
	public partial interface IPageHeader : IPublishedContent
	{
		/// <summary>Page Header Background</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.10.0")]
		global::Umbraco.Core.Models.PublishedContent.IPublishedContent PageHeaderBackground { get; }

		/// <summary>Page Heading</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.10.0")]
		string PageHeading { get; }
	}

	/// <summary>Page Header</summary>
	[PublishedModel("pageHeader")]
	public partial class PageHeader : PublishedContentModel, IPageHeader
	{
		// helpers
#pragma warning disable 0109 // new is redundant
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.10.0")]
		public new const string ModelTypeAlias = "pageHeader";
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.10.0")]
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.10.0")]
		public new static IPublishedContentType GetModelContentType()
			=> PublishedModelUtility.GetModelContentType(ModelItemType, ModelTypeAlias);
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.10.0")]
		public static IPublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<PageHeader, TValue>> selector)
			=> PublishedModelUtility.GetModelPropertyType(GetModelContentType(), selector);
#pragma warning restore 0109

		// ctor
		public PageHeader(IPublishedContent content)
			: base(content)
		{ }

		// properties

		///<summary>
		/// Page Header Background: Select image to be displayed in background of header.
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.10.0")]
		[ImplementPropertyType("pageHeaderBackground")]
		public global::Umbraco.Core.Models.PublishedContent.IPublishedContent PageHeaderBackground => GetPageHeaderBackground(this);

		/// <summary>Static getter for Page Header Background</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.10.0")]
		public static global::Umbraco.Core.Models.PublishedContent.IPublishedContent GetPageHeaderBackground(IPageHeader that) => that.Value<global::Umbraco.Core.Models.PublishedContent.IPublishedContent>("pageHeaderBackground");

		///<summary>
		/// Page Heading
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.10.0")]
		[ImplementPropertyType("pageHeading")]
		public string PageHeading => GetPageHeading(this);

		/// <summary>Static getter for Page Heading</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.10.0")]
		public static string GetPageHeading(IPageHeader that) => that.Value<string>("pageHeading");
	}
}
